### ISSUE TITLE
Sometimes modules get tagged when there's no actual code change

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/gha-gauge-release#6]
Sometimes, a release is being made even when there's no code change, e.g. https://github.com/silverstripe/silverstripe-framework/releases/tag/5.0.20 -- actual code diff - https://github.com/silverstripe/silverstripe-framework/compare/5.0.19..5.0.20

The scenarios that can cause this are:
1. A change is made in 5.0 and tagged, and then backported to 4.13, and merged back up to 5.0 - this will get auto-tagged again but this second tag in 5.0 won't have any actual code change.
2. A change will be made in CMS 4 that we don't want to keep in CMS 5, so it's reverted in the merge up. Again, this will be auto-tagged with no code change. 

## Acceptance criteria
- patches aren't tagged if there's no change since the last tag.

## notes
- we _could_ explicitly check if the code changes in the diff come from one of the commits that contributes to this being worth tagging (i.e validate that the code changes don't belong only to MNT commits), but that's likely overkill.

## PRs
- https://github.com/silverstripe/gha-gauge-release/pull/7

**Comment by ChloeSartorelli** [comment]
PR merged
